version: "3"

services:

  proxy:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    depends_on:
      - nb0
      - nb1
  nb0:
    build:
      context: .
      dockerfile: notebook.dockerfile

  nb1:
    build:
      context: .
      dockerfile: notebook.dockerfile
